name = "api"
type = "javascript"
usage_model = ''
compatibility_flags = []
workers_dev = true
webpack_config = "webpack.config.js"

[durable_objects]
bindings = [
  { name = "USERS", class_name = "Users" },
  { name = "AIRDROP", class_name = "Airdrop" },
  { name = "FOUNDER_NFT", class_name = "FounderNft"}
]

[build]
command = "yarn install && yarn build"

[build.upload]
format = "modules"
main = "./index.mjs"

[env.production]
route = 'api.shroomkingdom.net/*'
zone_id = 'f0cc6af324b9ef33f40a1ef5edf5b1fd'
