name = "api"
type = "webpack"
usage_model = ''
compatibility_flags = []
workers_dev = true
webpack_config = "webpack.config.js"

[build]
command = "yarn install && yarn build"
[build.upload]
format = "service-worker"

[env.production]
route = 'api.shroomkingdom.net/*'
zone_id = 'f0cc6af324b9ef33f40a1ef5edf5b1fd'
